apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  # SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
  EUREKA_APPLICATION_NAME: eurekaserver
  ACCOUNTS_APPLICATION_NAME: accounts


  kubectl apply -f 2_zipkin.yml
  kubectl apply -f 3_configserver.yml
  kubectl apply -f 4_eurekaserver.yml
  kubectl apply -f 5_accounts.yml
